from lib.database_utils import DatabaseUtils
import json
import os

def create_applicants_table():
    db.drop_table("Applicants")
    db.create_table("""
        CREATE TABLE Applicants(
            p_id int GENERATED BY DEFAULT AS IDENTIFY PRIMARY KEY,
            program TEXT,
            comments TEXT,
            date_added date,
            url TEXT,
            status TEXT,
            term TEXT,
            us_or_international TEXT,
            gpa float,
            gre float,
            gre_v float,
            gre_aw float,
            degree TEXT);
   """)

def load_data(filename):
    try:
        with open(filename, 'r', encoding='utf-8') as f:
            data = json.load(f)
        print(f"Data saved to {filename}. {f.name}")
    except FileNotFoundError:
        print(f"Error: File '{filename}' not found.")
    except json.JSONDecodeError:
        print(f"Error: File '{filename}' contains invalid JSON.")
    except Exception as e:
        print(f"Unexpected error reading JSON file: {e}")
    return data

def insert_applicants(data):
    for applicant in data:
        db.execute_query("""
            INSERT INTO Applicants(program, comments, date_added,url,
                status,term,us_or_international,gpa,gre,gre_v,gre_aw, degree)
                VALUES (%s,%s,%s,%s,%s,%s,%s,%f,%f,%f,%f,%s)
       """, applicant)

if __name__ == "__main__":
    conninfo = "postgresql:///grandcafedatabase"
    db = DatabaseUtils(conninfo, 5, 10)
    path = f"{os.getcwd()}/module_2/applicant_data.json"
    data = load_data(path)
    create_applicants_table()
    insert_applicants(data)